// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMsHP9F3H8yXoXNObPJmGYLlojUInsqo',
    appId: '1:318959128833:web:32eeb23f81c40ba61ecb00',
    messagingSenderId: '318959128833',
    projectId: 'babischool-90241',
    authDomain: 'babischool-90241.firebaseapp.com',
    storageBucket: 'babischool-90241.firebasestorage.app',
    measurementId: 'G-389Y9G2BYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UdAat8fp1vrfvjatmc6tTNYlhlDBGwY',
    appId: '1:318959128833:android:1a044b6901dd9a061ecb00',
    messagingSenderId: '318959128833',
    projectId: 'babischool-90241',
    storageBucket: 'babischool-90241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Okbeef4V2m9xuPXFxZ1gckW3LOpNngY',
    appId: '1:318959128833:ios:64f67dc33d054e3b1ecb00',
    messagingSenderId: '318959128833',
    projectId: 'babischool-90241',
    storageBucket: 'babischool-90241.firebasestorage.app',
    iosBundleId: 'com.example.babischoolMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Okbeef4V2m9xuPXFxZ1gckW3LOpNngY',
    appId: '1:318959128833:ios:64f67dc33d054e3b1ecb00',
    messagingSenderId: '318959128833',
    projectId: 'babischool-90241',
    storageBucket: 'babischool-90241.firebasestorage.app',
    iosBundleId: 'com.example.babischoolMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKMsHP9F3H8yXoXNObPJmGYLlojUInsqo',
    appId: '1:318959128833:web:51e13154a437cd331ecb00',
    messagingSenderId: '318959128833',
    projectId: 'babischool-90241',
    authDomain: 'babischool-90241.firebaseapp.com',
    storageBucket: 'babischool-90241.firebasestorage.app',
    measurementId: 'G-E92N22X3FX',
  );
}
